name: nfs-server-buildx

on:
  schedule:
    - cron: "20 4 * * Sun"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: N0rthernL1ghts/docker-nfs-server
          path: ./docker-nfs-server

      - name: Use Apache Flink free_disk_space.sh
        run: |
          curl -L 'https://raw.githubusercontent.com/apache/flink/02d30ace69dc18555a5085eccf70ee884e73a16e/tools/azure-pipelines/free_disk_space.sh' -o ./free_disk_space.sh
          chmod +x ./free_disk_space.sh
          ./free_disk_space.sh
          rm -f ./free_disk_space.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build nfs-server locally
        uses: docker/build-push-action@v2
        with:
          context: ./docker-nfs-server
          file: ./docker-nfs-server/Dockerfile
          load: true
          tags: lewadik/nfs-server-local:latest

      - name: Get nfs-utils version
        run: |
          version=$(docker run -i --rm lewadik/nfs-server-local apk list | grep -E '^nfs-utils' | cut -d' ' -f1 | cut -d'-' -f3)
          echo version=$version >> $GITHUB_ENV

      - name: Build and push nfs-server
        uses: docker/build-push-action@v2
        with:
          context: ./docker-nfs-server/
          file: ./docker-nfs-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lewadik/nfs-server:latest,lewadik/nfs-server:${{ env.version }}
